platform :ios, '7.0'
xcodeproj '00Promise.xcodeproj'

pod 'AFNetworking', '< 1.9.9'
pod 'JSONKit',       '~> 1.4'
pod 'LBBlurredImage'
pod 'FSExtendedAlertKit'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'ODRefreshControl', '~> 1.1.0'
pod 'VKDAKeyboardControl', '~> 2.3.0'
pod 'NSRails'
pod 'CJStringValidator'
pod 'AMScrollingNavbar'